name: Build and Publish Container

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: Dockerfile
          context: .

      - name: Build Docker Image
        run: docker build -t ${{ secrets.GITHUB_REPOSITORY }} .

      - name: Authenticate to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Tag Docker Image
        run: docker tag ${{ secrets.GITHUB_REPOSITORY }} docker.pkg.github.com/${{ secrets.GITHUB_REPOSITORY }}/conteneur:latest

      - name: Push Docker Image to GitHub Packages
        run: docker push docker.pkg.github.com/${{ secrets.GITHUB_REPOSITORY }}/conteneur:latest
