name: Build and Run Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile
        context: .

    - name: Build Docker image
      run: docker build -t test:tag .

    - name: Run Docker container
      run: docker run -p 5000:5000 test:tag
